### ISSUE TITLE
Game crashes with the "Russia Completely Divided" option

### ISSUE THREAD

**Issue by InsurGentleman** [DRAFTik/Kursach-Fizika#13]
I know this probably isn't one of the first priorities to fix, it is just an extra game option for the releasables stuff, but I noticed no one put this here, so I thought I'd mention it. The other releasable status options for the Soviet Union and other countries seem to work fine, just Russia crashes the game when you select the second option to release everything.

**Comment by Kama-Pushka** [comment]
we have cut out this option, maybe it will return in the future
thanks for the report, no one remembered to reply to you during this time
