### ISSUE TITLE
Игра крашится из-за какого-то ивента в бельгийском Конго

### ISSUE THREAD

**Issue by gosha875** [DRAFTik/Kursach-Fizika#18]
Нашёл лог с ивентом здесь:
[game.log](https://github.com/DRAFTik/Kursach-Fizika/files/13794489/game.log)

В целом папка с логами если надо:
[logs.zip](https://github.com/DRAFTik/Kursach-Fizika/files/13794495/logs.zip)

Ещё спросить хотел почему в логах иногда бельгийское Конго извергает в консоль GAY SEX?

**Comment by Kama-Pushka** [comment]
ахахаха вот что бывает когда играешь в дев версию)
